---
title: "Simulation"
author: "Quinn White"
date: "`r Sys.Date()`"
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_dir = "../output")})
output: 
  rmdformats::readthedown:
    code_folding: hide
    df_print: paged
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE,message=FALSE, warning=FALSE)

library(tidyverse)
theme_c <- function(...){ 
   # font <- "Helvetica"   #assign font family up front
  #  font <- "Arial"
    theme_bw() %+replace%    #replace elements we want to change
    
    theme(
      
      #text elements
      plot.title = element_text(             #title
                 #  family = font,            #set font family
                   size = 11,                #set font size
                   face = 'bold',            #bold typeface
                   hjust = .5,
                   vjust = 3),               
      
      plot.subtitle = element_text(          #subtitle
                #   family = font,            #font family
                   size = 10,
                   hjust = .5,
                   face = 'italic',
                   vjust = 3),               #font size
      
      axis.title = element_text(             #axis titles
                #   family = font,            #font family
                   size = 10),               #font size
      
      axis.text = element_text(              #axis text
                #   family = font,            #axis famuly
                   size = 8),
      strip.text = element_text(color="white", size = 9,
                                margin=unit(c(.1,.1,.1,.1), 'cm')),
      strip.background = element_rect(fill = "#363636"),
      # t, r, b, l
      plot.margin = unit(c(1,.5,.5,.5), "cm")
      ) %+replace%
      theme(...)
   
}


```

Let $L_k$ be an indicator for having high blood pressure. Let $A$ be the treatment assigment (e.g., an ACE inhibitor).

Direct effect:

\begin{align*}
\text{Direct effect}&=\Pr[Y_{k+1}^{a=1, \overline{d=0}}=1]- \Pr[Y_{k+1}^{a=0, \overline{d=0}}=1] \\& = 0.5(0.2+0.1) - 0.5(.3+0.25)\\
&= -0.125
\end{align*}

Total effect:




```{r}

n <- 1000

set.seed(999)
baseline <- tibble(
  # baseline covariates
  l0 = rbinom(n, 1, .5),
  # treatment assigment
  a0 = rbinom(n, 1, .5),
  time_point = 1,
  participant_id = 1:n)


A1_L1_P_D <- .12 
A1_L0_P_D <- .05
A0_L1_P_D <- .1
A0_L0_P_D <- .08


A1_L1_P_Y <- .2
A1_L0_P_Y <- .1
A0_L1_P_Y <- .3
A0_L0_P_Y <- .25


##########################
# FIRST TIME POINT 
########################## 


sim_dat <- map_df(1:n, ~ {
   baseline[.x,] %>%
     mutate(dk = case_when(
      a0 == 1 & l0 == 1 ~ rbinom(1,1, A1_L1_P_D),
      a0 == 1 & l0 == 0 ~ rbinom(1,1, A1_L0_P_D),
      a0 == 0 & l0 == 1 ~ rbinom(1,1,  A0_L1_P_D),
      a0 == 0 & l0 ==0 ~ rbinom(1, 1, A0_L0_P_D)
    ),
    dk_A_0 = case_when(
      # consistency 
      a0 == 0 ~ dk,
      # if a0 == 1 and l0 == 1, simulate as if a0 == 0 and l0 == 1
      a0 == 1 & l0 == 1 ~ rbinom(1,1, A0_L1_P_D),
      # if a0 == 1 and l0 == 0, simulate as if a0 == 0 and l0 == 0
      a0 == 1 & l0 == 0 ~ rbinom(1, 1, A0_L0_P_D)),
    dk_A_1 = case_when(
      # consistency
      a0 == 1 ~ dk,
      # if a0 == 0 and l0 == 1, simulate as if a0 == 1 and l0 ==1
      a0 == 0 & l0 == 1 ~ rbinom(1,1, A1_L1_P_D),
      # if a0 == 0 and l0 == 0, simulate as if a0 == 1 and l0 ==0
      a0 == 0 & l0 ==0 ~ rbinom(1,1, A1_L0_P_D)
    ),
    yk = case_when(
      # if they have the competing event, cannot have the event of interest
      dk == 1 ~ 0, 
      a0 == 1 & l0 == 1 ~ rbinom(1,1, A1_L1_P_Y),
      a0 == 1 & l0 == 0 ~ rbinom(1,1, A1_L0_P_Y),
      a0 ==0 & l0 == 1 ~ rbinom(1,1, A0_L1_P_Y),
      a0 == 0 & l0 ==0 ~ rbinom(1, 1, A0_L0_P_Y)
    ),
    yk_A_0 = case_when(
       # if they have the competing event, cannot have the event of interest
      # this remains true when considering a0 == 0
      dk == 1 ~ 0, 
      # consistency
      a0 == 0 ~ yk,
      # simulate as if they had a0 == 0 and l0 == 1
      a0 == 1 & l0 == 1 ~ rbinom(1,1,A0_L1_P_Y),
      # simulate as if they had a0 == 0 and l0 == 0
      a0 == 1 & l0 == 0 ~ rbinom(1,1, A0_L0_P_Y)
    ),
      yk_A_1 = case_when(
       # if they have the competing event, cannot have the event of interest
      # this remains true when considering a0 == 0
      dk == 1 ~ 0, 
      # consistency
      a0 == 1 ~ yk,
      # simulate as if they had a0 == 1 and l0 == 1
      a0 == 0 & l0 == 1 ~ rbinom(1,1,A1_L1_P_Y),
      # simulate as if they had a0 == 0 and l0 == 0
      a0 == 0 & l0 == 0 ~ rbinom(1,1, A1_L0_P_Y)
    ),
    yk_A_0_D_0 = case_when(
      # simulate as if they had no competing event and a0==0
      # consistency 
      dk == 0 & a0 == 0 ~ yk,
      # use previously generated potential outcomes when dk=0
      dk == 0 & a0 == 1 & l0 == 1 ~ yk_A_0,
      dk == 0 & a0 == 1 & l0 == 0 ~ yk_A_0,
      # when dk = 1 generate potential outcomes for these cases 
      dk == 1 & a0 %in% c(0,1) & l0 == 1 ~ rbinom(1,1, A0_L1_P_Y),
      dk == 1 & a0 %in% c(0,1) & l0 == 0 ~ rbinom(1,1, A0_L0_P_Y)
    ),
    yk_A_1_D_0 = case_when(
      # simulate as if they had no competing event and a0==1
      # consistency 
      dk == 0 & a0 == 1 ~ yk,
      # use previously generated potential outcomes when dk=0
      dk == 0 & a0 == 0 & l0 == 1 ~ yk_A_1,
      dk == 0 & a0 == 0 & l0 == 0 ~ yk_A_1,
      # when dk = 1 generate potential outcomes for these cases 
      dk == 1 & a0 %in% c(0,1) & l0 == 1 ~ rbinom(1,1, A1_L1_P_Y),
      dk == 1 & a0 %in% c(0,1) & l0 == 0 ~ rbinom(1,1, A1_L0_P_Y)
    )
    )})


##################################
# EFFECT OF L_0 ON L_1
##################################
L1_GIVEN_L0_P = .2
L1_GIVEN_L1_P = .8


###############################
# CENSORING PROBABILITIES
###############################
# probability of censoring if L_1 = 0
C_K1_GIVEN_L1 = .08
# probability of censoring if L_0 = 0
C_K1_GIVEN_L0 = .04


#################################################
# PROBABILITIES OF HAVING COMPETING EVENT 
# UNDER EACH TREATMENT x L1 COMBINATION 
#################################################
A1_L1_P_D_K1 <- A1_L1_P_D + .04
A1_L0_P_D_K1 <- A1_L0_P_D + .02
A0_L1_P_D_K1 <- A0_L1_P_D + .06
A0_L0_P_D_K1 <- A0_L0_P_D + .03


#################################################
# PROBABILITIES OF HAVING EVENT OF INTEREST 
# UNDER EACH TREATMENT x L1 COMBINATION 
#################################################
A1_L1_P_Y_K1 <- A1_L1_P_Y + .035
A1_L0_P_Y_K1 <- A1_L0_P_Y + .025
A0_L1_P_Y_K1 <- A0_L1_P_Y + .055
A0_L0_P_Y_K1 <- A0_L0_P_Y + .025



################################
# ADD TIME POINT Y_{K+1}
################################
 sim_dat_updated <- map_df(1:2, ~{
   
   sim_dat[.x,] %>%
     mutate(l1 = case_when(
       # set to previous value if had either event of interest or competing event
       dk == 1 | yk == 1 ~ l0,
       l0 == 0 ~ rbinom(1,1, L1_GIVEN_L0_P),
       l0 == 1 ~  rbinom(1,1, L1_GIVEN_L1_P)
       ),
       
      c_k1 = case_when(
        # if we observed either event previously, they are not censored
        dk == 1 | yk == 1 ~ 0,
        l1 == 1 ~ rbinom(1,1, C_K1_GIVEN_L1),
        l1 == 1 ~ rbinom(1,1, C_K1_GIVEN_L0)
        ),
      d_k1 = case_when(
        yk == 1 ~ 0,
        dk == 1 ~ 1,
        c_k1 == 1 ~ NA,
        a0 == 1 & l1 == 1 ~ rbinom(1,1, A1_L1_P_D_K1),
        a0 == 1 & l1 == 0 ~ rbinom(1,1, A1_L0_P_D_K1),
        a0 == 0 & l1 == 1 ~ rbinom(1,1,  A0_L1_P_D_K1),
        a0 == 0 & l1 ==0 ~ rbinom(1, 1, A0_L0_P_D_K1)
      ),
      
  
    ###########################
    # OBSERVED COMPETING EVENT
    ###########################
     d_k1 = case_when(
        yk == 1 ~ 0,
        dk == 1 ~ 1,
        c_k1 == 1 ~ NA,
        a0 == 1 & l1 == 1 ~ rbinom(1,1, A1_L1_P_D_K1),
        a0 == 1 & l1 == 0 ~ rbinom(1,1, A1_L0_P_D_K1),
        a0 == 0 & l1 == 1 ~ rbinom(1,1,  A0_L1_P_D_K1),
        a0 == 0 & l1 ==0 ~ rbinom(1, 1, A0_L0_P_D_K1)
      ),
    
    ##############################################
    # COUNTERFACTUALS FOR COMPETING EVENT
    ##############################################
    # useful if we want to calculate effect of treatment on competing event
    
    # counterfactual under yk = 0, dk = 0, c_{k+1}=0, A=0 (needed for direct effect )
    d_k1_Y0_D0_C0_A_0 = case_when(
      # consistency 
      yk ==0 & dk == 0 & a0 == 0 & c_k1 == 0 ~ d_k1,
      # otherwise, have to generate new d_k1 
      # if a0 == 1 or 0 and l0 == 1, simulate as if a0 == 0 and l0 == 1
      a0 %in% c(0,1) & l1 == 1 ~ rbinom(1,1, A0_L1_P_D_K1),
      # if a0 == 1 or 0 and l0 == 0, simulate as if a0 == 0 and l0 == 0
      a0 %in% c(0,1) & l1 == 0 ~ rbinom(1, 1, A0_L0_P_D_K1),
      ),
    
    # counterfactual under yk = 0, dk = 0, ck=0, A=1 (needed for direct effect )
    d_k1_Y0_D0_C0_A_1 = case_when(
      # consistency 
      yk ==0 & dk == 0 & a0 == 1 & c_k1 == 0 ~ d_k1,
      # otherwise, have to generate new d_k1 
      # if a0 == 1 and l0 == 1, simulate as if a0 == 0 and l0 == 1
      a0 %in% c(0,1) & l1 == 1 ~ rbinom(1, 1, A1_L1_P_D_K1),
      # if a0 == 1 and l0 == 0, simulate as if a0 == 0 and l0 == 0
      a0 %in% c(0,1) & l1 == 0 ~ rbinom(1, 1, A1_L0_P_D_K1)
      ),
    
    # counterfactual under yk = 0, ck=0, a=0 (needed for total effect )
    d_k1_Y0_C0_A_0 = case_when(
      # set competing event to 1 if they had a previous event
      dk == 1 ~ 1,
      # consistency 
      yk ==0 & a0 == 0 & c_k1 == 0 ~ d_k1,
      # otherwise, need to generate new outcome 
      # if a0 == 1 or 0 and l0 == 0, simulate as if a0 == 0 and l0 == 0
      a0 %in% c(0,1) & l1 == 0 ~ rbinom(1, 1, A0_L0_P_D_K1),
      # if a0 == 1 or 0 and l0 == 1, simulate as if a0 == 0 and l0 == 1
      a0 %in% c(0,1) & l1 == 1 ~ rbinom(1,1, A0_L1_P_D_K1),
      ),
    
    # counterfactual under yk=0, ck=0, a= 1 (needed for total effect )
    d_k1_Y0_C0_A_1 = case_when(
      # set competing event to 1 if they had a previous event
      dk == 1 ~ 1,
      # consistency 
      yk ==0 & a0 == 0 & c_k1 == 0 ~ d_k1,
      # otherwise, need to generate new outcome 
      # if a0 == 1 or 0 and l0 == 1, simulate as if a0 == 0 and l0 == 1
      a0 %in% c(0,1) & l1 == 1 ~ rbinom(1,1, A1_L1_P_D_K1),
      # if a0 == 1 or 0 and l0 == 0, simulate as if a0 == 0 and l0 == 0
      a0 %in% c(0,1) & l1 == 0 ~ rbinom(1, 1, A1_L0_P_D_K1)
      ),
    
    
    ##################################
    # OBSERVED EVENT OF INTEREST
    ##################################
     y_k1 = case_when(
        yk == 1 ~ 1,
        dk == 1 ~ 0,
        c_k1 == 1 ~ NA,
        a0 == 1 & l1 == 1 ~ rbinom(1,1, A1_L1_P_Y_K1),
        a0 == 1 & l1 == 0 ~ rbinom(1,1, A1_L0_P_Y_K1),
        a0 == 0 & l1 == 1 ~ rbinom(1,1,  A0_L1_P_Y_K1),
        a0 == 0 & l1 ==0 ~ rbinom(1, 1, A0_L0_P_Y_K1)
      ),
    
    
    ##############################################
    # COUNTERFACTUALS FOR EVENT OF INTEREST 
    ##############################################

    # counterfactual under yk = 0, d_{k+1} = 0, c_{k+1}=0, A=0 (needed for direct effect)
    y_k1_Y0_D0_C0_A_0 = case_when(
      # consistency 
      yk ==0 & d_k1 == 0 & a0 == 0 & c_k1 == 0 ~ y_k1,
      # otherwise, have to generate new y_k1 
      # if a0 == 1 or 0 and l1 == 1, simulate as if a0 == 0 and l1 == 1
      a0 %in% c(0,1) & l1 == 1 ~ rbinom(1,1, A0_L1_P_Y_K1),
      # if a0 == 1 or 0 and l0 == 0, simulate as if a0 == 0 and l1 == 0
      a0 %in% c(0,1) & l1 == 0 ~ rbinom(1, 1, A0_L0_P_Y_K1),
      ),
    
    # counterfactual under y_{k} = 0, d_{k+1} = 0, c_{k+1}=0, A=1 (needed for direct effect)
    y_k1_Y0_D0_C0_A_1 = case_when(
      # consistency 
      yk ==0 & d_k1 == 0 & a0 == 1 & c_k1 == 0 ~ y_k1,
      # otherwise, have to generate new y_k1 
      # if a0 == 1 and l1 == 1, simulate as if a0 == 0 and l1 == 1
      a0 %in% c(0,1) & l1 == 1 ~ rbinom(1, 1, A1_L1_P_Y_K1),
      # if a0 == 1 and l1 == 0, simulate as if a0 == 0 and l1 == 0
      a0 %in% c(0,1) & l1 == 0 ~ rbinom(1, 1, A1_L0_P_Y_K1)
      ),
    
    # counterfactual under y_{k} = 0, c_{k+1}=0, A=0 (needed for total effect )
    y_k1_Y0_C0_A_0 = case_when(
      # set competing event to 1 if they had a previous event
      yk == 1 ~ 1,
      # we are not eliminating possbility of past competing event
      dk == 1 ~ 0, 
      # consistency 
      yk ==0 & a0 == 0 & c_k1 == 0 ~ y_k1,
      # otherwise, need to generate new outcome 
      # if a0 == 1 or 0 and l1 == 0, simulate as if a0 == 0 and l1== 0
      a0 %in% c(0,1) & l1 == 0 ~ rbinom(1, 1, A0_L0_P_D_K1),
      # if a0 == 1 or 0 and l1 == 1, simulate as if a0 == 0 and l1 == 1
      a0 %in% c(0,1) & l1 == 1 ~ rbinom(1,1, A0_L1_P_D_K1),
      ),

    # counterfactual under y_{k} = 0, c_{k+1}=0, A=1 (needed for total effect)
    y_k1_Y0_C0_A_1 = case_when(
      # set competing event to 1 if they had a previous event
      yk == 1 ~ 1,
      # we are not eliminating possibility of past competing event
      dk == 1 ~ 0, 
      # consistency 
      yk ==0 & a0 == 1 & c_k1 == 0 ~ y_k1,
      # otherwise, need to generate new outcome 
      # if a0 == 1 or 0 and l0 == 0, simulate as if a0 == 0 and l0 == 0
      a0 %in% c(0,1) & l1 == 0 ~ rbinom(1, 1, A1_L0_P_D_K1),
      # if a0 == 1 or 0 and l0 == 1, simulate as if a0 == 0 and l0 == 1
      a0 %in% c(0,1) & l1 == 1 ~ rbinom(1,1, A1_L1_P_D_K1),
      )
     )
 })
 
 
 
        
        


label_a <- function(string, prefix = "A=") paste0(prefix, string)
label_l <- function(string, prefix = "L=") paste0(prefix, string)


# sim_dat %>%
#   pivot_longer(cols=contains("k")) %>%
#   group_by(name,l0, a0) %>%
#   summarize(prop = sum(value) /n()) %>%
#   ggplot(aes(y= name, x = prop)) +
#   geom_bar(stat="identity") +
#   facet_grid(l0~a0, labeller = labeller(a0=label_a, l0 = label_l)) +
#   theme_c()



sim_dat %>%
  pivot_longer(cols=contains("k")) %>%
  group_by(name,l0, a0) %>%
  mutate(a0 = ifelse(a0 == 0, "Control", "Treatment")) %>%
  summarize(prop = sum(value) /n()) %>%
  ggplot(aes(y= name, x = prop, fill = factor(a0))) +
  geom_bar(stat="identity", position="dodge", alpha=.8) +
  facet_wrap(~l0, labeller = labeller( l0 = label_l)) +
  theme_c() +
  labs(fill="", x= "Proportion who had Event") +
  viridis::scale_fill_viridis(discrete=TRUE, 
                              begin=.1, 
                              end=.8) 



```


True average causal effect
